"""Pack the PyInstaller one-file FinWise binary into a proper macOS .app bundle.

Run AFTER build_exe.py on macOS (or from the macOS CI runner). Produces:
    backend/dist_finwise/FinWise.app/Contents/MacOS/FinWise   (the binary)
    backend/dist_finwise/FinWise.app/Contents/Info.plist
    backend/dist_finwise/FinWise.app/Contents/Resources/  (icon + data dirs)

The app is a normal console binary (NOT --windowed), so it writes logs to a
terminal when launched from Terminal; when double-clicked, macOS auto-opens a
Terminal window for it. Clicking the .app starts the server and prints the URL.

Usage:  python pack_mac_app.py
"""
from __future__ import annotations

import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent           # backend/
DIST = HERE / "dist_finwise"
BIN = DIST / "FinWise"                            # produced by build_exe.py
APP = DIST / "FinWise.app"

APP_NAME = "FinWise"
BUNDLE_ID = "app.finwise.desktop"

# Optional icon: backend/finwise.icns (generated by make_icns.py on macOS).
ICNS = HERE / "finwise.icns"


def main() -> int:
    if sys.platform != "darwin":
        # We can still create the structure for inspection, but the binary is
        # only a Mach-O when built on macOS; warn and continue only on darwin.
        print("[pack_mac_app] WARNING: not on macOS. The .app will be packed "
              "but the binary is not a Mach-O here; build on macOS for a runnable bundle.",
              file=sys.stderr)
        if not BIN.exists():
            print(f"[pack_mac_app] ERROR: {BIN} not found. Run build_exe.py on macOS first.",
                  file=sys.stderr)
            return 2

    if not BIN.exists():
        print(f"[pack_mac_app] ERROR: {BIN} not found. Run build_exe.py first.", file=sys.stderr)
        return 2

    # Clean and create the bundle skeleton.
    if APP.exists():
        shutil.rmtree(APP, ignore_errors=True)
    macos = APP / "Contents" / "MacOS"
    res = APP / "Contents" / "Resources"
    macos.mkdir(parents=True, exist_ok=True)
    res.mkdir(parents=True, exist_ok=True)

    # Move the one-file binary into the bundle.
    target_bin = macos / APP_NAME
    shutil.move(str(BIN), str(target_bin))
    target_bin.chmod(0o755)

    # Info.plist
    info = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleVersion": "1.0.0",
        "CFBundleShortVersionString": "1.0.0",
        "CFBundlePackageType": "APPL",
        "CFBundleExecutable": APP_NAME,
        "LSMinimumSystemVersion": "10.15",
        "NSHighResolutionCapable": True,
        "NSRequiresAquaSystemAppearance": False,
        "CFBundleInfoDictionaryVersion": "6.0",
    }
    if ICNS.exists():
        shutil.copy(ICNS, res / "app.icns")
        info["CFBundleIconFile"] = "app"

    (APP / "Contents" / "Info.plist").write_bytes(plistlib.dumps(info))

    print(f"[pack_mac_app] Created {APP}")
    print(f"[pack_mac_app] Binary: {target_bin}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
