org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false

# Release signing (local keystore, keep private in real deployments)
FINWISE_STORE_FILE=finwise-release.keystore
FINWISE_STORE_PASSWORD=cCjBW4JvrfZMhA3SFHypzmKk
FINWISE_KEY_ALIAS=finwise
FINWISE_KEY_PASSWORD=cCjBW4JvrfZMhA3SFHypzmKk
